services:
  ai-api:
    #command: tail -f /dev/null
    build:
      context: ./ai-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./ai-api/.env
    volumes:
      - ./ai-api:/app

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres



