services:
  ai-api:
    #command: tail -f /dev/null
    build:
      context: ./ai-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./ai-api/.env
    volumes:
      - ./ai-api:/app

